### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by andrew** [librariesio/os-data-hackday#1]
Add your ideas of things to work on, build or improve that could help open source projects, users and maintainers.

**Comment by lewisnyman** [comment]
One thing I've experienced is the huge silent majority of users that never contribute back to a project. Even opening an issue or sharing a fork is valuable, even non-code contributions like writing an article, giving a presentation or organising an event.

There are many barriers to contribution, on-boarding, documentation, appreciation, etc

Has anyone else thought about this or tackling one of these barriers?

**Comment by andrew** [comment]
@lewisnyman a problem we run into on http://24pullrequests.com most years, even when people do contribute to a project they might never hear back from the maintainers which can be really disheartening for people new to open source, often resulting in them never coming back to contribute again.

I experimented with trying to suggest good projects to contribute to with https://contribulator.herokuapp.com/ last year but I've not done anything with it recently.

**Comment by M-Zuber** [comment]
There are a lot of different small projects out there to measure different aspects of projects (most based off of github, but majority of algorithms should be portable). 
For example:
- Time to issue close
- Time to response on opened issue.
- Ect.
  I will try and update with links when I get a chance to look for them, but a similar set of stats displayed on a projects page within libraries.io (and I know there are already a number of such things you measure) would help people looking for a project to contribute too - or even use as many people prefer to only use maintained projects.

## 

That is my little brain dump. Probing me may lead to more coherent thoughts.

**Comment by andrew** [comment]
@M-Zuber I've actually got those two features on the roadmap: https://github.com/librariesio/libraries.io/issues/472 https://github.com/librariesio/libraries.io/issues/473

I've collected almost enough issue data to be able to do it for every project with a github repository now as well, just need to index them in elasticsearch so that they can be easily queried

**Comment by M-Zuber** [comment]
Back to the drawing board then. :grinning:

**Comment by samjacobclift** [comment]
@andrew how about improving docs and setup guide for libraries? So people can contribute easier? I've set it up on my machine but was missing a few steps

**Comment by andrew** [comment]
@royka Yeah that would be great, I've not been the best at that so far tbh

**Comment by andrew** [comment]
Some more ideas:
- Add more API endpoints to allow more people build things on top of it: https://github.com/librariesio/libraries.io/issues/197
- Create a weekly "Trending" email: https://github.com/librariesio/libraries.io/issues/550
- Help Wanted - list github issues labelled with "help wanted" ordered by how depended upon the repository is: https://github.com/librariesio/libraries.io/issues/471
- Bots for sending pull requests to update dependencies on a project automatically after new versions are released
- Visualization of the dependency graph of a project or github repository
- Visualization of the dependency graph of a whole package manager (if you're feeling adventurous!)
- License compatibility investigation - Find out how many projects depend on copyleft libraries but aren't copyleft themselves.
- Badges - svg badges that can be embedded in github repos showing info about dependencies, source rank etc: https://github.com/librariesio/libraries.io/issues/75
