### ISSUE TITLE
Add start/end time details to README

### ISSUE THREAD

**Issue by leggetter** [librariesio/os-data-hackday#2]
What time does hacking start and end for all?

What time can people get into the London location and what time do they have to leave?

I'm pretty flexible with the latter. Any time from 8am to 10pm is fine with me. I just think it's worth clarifying on the README and probably on Attending too.

**Comment by andrew** [comment]
How about 10am until 7pm?

**Comment by leggetter** [comment]
👍

**Comment by andrew** [comment]
Updated attending.io and the readme 👍

**Comment by leggetter** [comment]
Thanks, @andrew!
